#!/bin/sh
#-------------------------------------------------
# Configures the template repo for a fresh project
#-------------------------------------------------

# copies example .env file
cp env-example .env

# makes empty directories
mkdir -p template
